### ISSUE TITLE
Fix filenames for Brand and Logo 

### ISSUE THREAD

**Issue by haseebjkhan** [karstenrowe/kt-ds#33]
Have a look: http://cloud.haseebjkhan.com/ku1994C

**Comment by karstenrowe** [comment]
Why are we using GitHub issues?

Our focus should be Rich's repo for v2/3/4.

This is caused by the casing of the folders and files. I can help with a short term fix but it's not worth investigating any further.

**Comment by haseebjkhan** [comment]
@karstenrowe  Agree, we shouldn't use. Sprayshop just got broken (colours section coz of these casing issue) and the devs use it. So didn't wanted ourselves become a blocker for them.
